---
title: "Random Forests"
author: "Zuofu Huang"
output: html_document
---


# Housekeeping

```{r message=FALSE}
library(caret)
library(tidyverse)
library(clv)
library(TraMineR)
# library(Matrix)
# library(glmnet)
library(matrixcalc)

data <- read.csv("/Users/zuofuhuang/Desktop/reduceSeq/Transportation data/cleaned_data_noNA.csv")[,-c(1:3)]
colnames(data) <- c(format(seq(as.POSIXct("00:00:00", format = "%T"), 
                 as.POSIXct("23:59:00", format = "%T"), by = "1 min"), "%H:%M"))

data <- data %>%
  mutate_if(is.character, as.factor)

extract_time <- function(string){
  as.numeric(substring(string, 2, 3)) * 60 + as.numeric(substring(string, 5, 6)) + 1
}
```



```{r}
source("../../clust_assign_func.R")

seq_distances <- read.csv("/Users/zuofuhuang/Desktop/reduceSeq/Transportation data/sequences_dist_matrix_om.csv")[,-1]


hclust_real <- stats::hclust(as.dist(seq_distances), method = "complete")
fit_real <- cutree(hclust_real, k = 23)
# table(fit_real)

cluster_assignment <- reorder_cluster_assignment(fit_real)

cluster_assignment[cluster_assignment > 14] <- 15
```

```{r}
data_CA <- data
data_CA$CA <- as.factor(cluster_assignment)
```


```{r}
# accuracy 2890/2892
# colnames(data_CA) <- make.names(colnames(data_CA))
# 
# set.seed(7003)
# random_forest <- train(as.factor(CA) ~ .,
#                     data = data_CA,
#                     method = "rf",
#                     trControl = trainControl(method = "cv", number = 10),
#                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)),
#                     ntree = 100)
# 
# sum(predict(random_forest, type = "raw") == cluster_assignment)
# table(predict(random_forest, type = "raw"), cluster_assignment) # top row is actual
```

```{r}
random_forest <- readRDS("RF_results_seed7003")

varImp(random_forest, scale = FALSE)
plot(random_forest$finalModel)
```

```{r}
important_variables <- as.data.frame(cbind(rownames(random_forest$finalModel$importance), random_forest$finalModel$importance))

important_variables$time <- extract_time(important_variables$V1)
important_variables$MeanDecreaseGini <- as.numeric(important_variables$MeanDecreaseGini)
```


# Individual thresholds

<!-- ```{r} -->
<!-- # Threshold of 1: Ran on seed 7026: 319 predictors with accuracy 2880/2892 -->
<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 1) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(7026) -->
<!-- rf1 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf1, "RF_threshold_1_results_seed7026") -->

<!-- sum(predict(rf1, type = "raw") == cluster_assignment) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # Threshold of 2: Ran on seed 7318: 214 predictors with accuracy 2874/2892 -->
<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 2) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(7318) -->
<!-- rf2 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf2, "RF_threshold_2_results_seed7318") -->

<!-- sum(predict(rf2, type = "raw") == cluster_assignment) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- # Threshold of 3: Ran on seed 7319: 156 predictors with accuracy 2847/2892 -->
<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 3) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(7319) -->
<!-- rf3 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf3, "RF_threshold_3_results_seed7319") -->

<!-- sum(predict(rf3, type = "raw") == cluster_assignment) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- # Threshold of 4: Ran on seed 7027: 92 predictors with accuracy 2790/2892 -->
<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 4) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(7027) -->
<!-- rf4 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf4, "RF_threshold_4_results_seed7027") -->

<!-- sum(predict(rf4, type = "raw") == cluster_assignment) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # Threshold of 4.5: Ran on seed 7501: 59 predictors with accuracy 2782/2892 -->
<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 4.5) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(7501) -->
<!-- rf4.5 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf4.5, "RF_threshold_4.5_results_seed7501") -->

<!-- sum(predict(rf4.5, type = "raw") == cluster_assignment) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # Threshold of 5: Ran on seed 7028: 30 predictors with accuracy 2762/2892 -->
<!-- # "00:04" "00:06" "02:43" "03:11" "03:17" "04:41" "06:16" "08:15" "08:24" "08:39" "09:21" "09:30" "09:39" -->
<!-- # "09:42" "10:34" "10:43" "11:11" "11:29" "11:56" "12:08" "12:29" "12:51" "12:53" "13:07" "13:17" "13:35" -->
<!-- # "14:01" "14:13" "14:29" "15:49" -->

<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 5) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(7028) -->
<!-- rf5 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf5, "RF_threshold_5_results_seed7028") -->

<!-- sum(predict(rf5, type = "raw") == cluster_assignment) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # Threshold of 5.2: Ran on seed 7555: 19 predictors with accuracy 2741/2892 -->

<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 5.2) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(7555) -->
<!-- rf5.2 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf5.2, "RF_threshold_5.2_results_seed7555") -->

<!-- sum(predict(rf5.2, type = "raw") == cluster_assignment) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- # Threshold of 6: Ran on seed 7355: 12 predictors with accuracy 2750/2892 -->
<!-- # 00:04 8:15 8:24 9:39 9:42 10:34 10:43 11:11 13:07 13:35 14:01 14:13 -->
<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 6) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(7355) -->
<!-- rf6 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf6, "RF_threshold_6_results_seed7355") -->

<!-- sum(predict(rf6, type = "raw") == cluster_assignment) -->
<!-- ``` -->




<!-- ```{r} -->
<!-- # Threshold of 6.5: Ran on seed 1001: 9 predictors with accuracy 2705/2892 -->
<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 6.5) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(1001) -->
<!-- rf6.5 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf6.5, "RF_threshold_6.5_results_seed1001") -->

<!-- sum(predict(rf6.5, type = "raw") == cluster_assignment) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- # Threshold of 7: Ran on seed 7356: 7 predictors with accuracy 2551/2892 -->
<!-- # 8:24 9:39 9:42 10:43 11:11 13:07 13:35 -->

<!-- this <- important_variables %>% -->
<!--   filter(MeanDecreaseGini > 7) -->

<!-- data_reduced <- data_CA[,c(unique(this$time),1441)] -->

<!-- set.seed(7356) -->
<!-- rf7 <- train(as.factor(CA) ~ ., -->
<!--                     data = data_reduced, -->
<!--                     method = "rf", -->
<!--                     trControl = trainControl(method = "cv", number = 10), -->
<!--                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)), -->
<!--                     ntree = 100) -->

<!-- # saveRDS(rf7, "RF_threshold_7_results_seed7356") -->

<!-- sum(predict(rf7, type = "raw") == cluster_assignment) -->
<!-- ``` -->





# Combine into one function (Select position * activity above a threshold and then select the entire time)

```{r}
# gini_thresholds <- seq(0.8, 7.2, by = 0.1)
# 
# iterations <- length(gini_thresholds)
# positions <- rep(NA, iterations)
# accuracy <- rep(NA, iterations)
# 
#   
# for (i in 1:iterations){
#   print(i)
#   this <- important_variables %>%
#     filter(MeanDecreaseGini > gini_thresholds[i])
#   
#   data_reduced <- data_CA[,c(unique(this$time),1441)]
#   positions[i] <- ncol(data_reduced) - 1
#   
#   set.seed(319)
#   rf_model <- train(as.factor(CA) ~ .,
#                     data = data_reduced,
#                     method = "rf",
#                     trControl = trainControl(method = "cv", number = 10),
#                     tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)),
#                     ntree = 100)
# 
#   accuracy[i] <- sum(predict(rf_model, type = "raw") == cluster_assignment)
# }
# 
# results <- cbind(iterations, positions, accuracy)
# 
# write.csv(results, "rf_position_activity.csv")
```





# Combine into one function (Add up all the activities of a position and then select position above a threshold)

```{r}
position_importance <- important_variables %>%
  group_by(time) %>%
  mutate(position_sum = sum(MeanDecreaseGini)) %>%
  select(time, position_sum) %>%
  unique()

combined_gini <- seq(1, 9.25, by = 0.15)

iterations <- length(combined_gini)
positions <- rep(NA, iterations)
accuracy <- rep(NA, iterations)


for (i in 1:iterations){
  print(i)
  this <- position_importance %>%
    filter(position_sum > combined_gini[i]) %>%
    pull(time)

  data_reduced <- data_CA[,c(this,1441)]

  positions[i] <- ncol(data_reduced) - 1

  set.seed(319)
  rf_model <- train(as.factor(CA) ~ .,
                    data = data_reduced,
                    method = "rf",
                    trControl = trainControl(method = "cv", number = 10),
                    tuneGrid = expand.grid(mtry = seq(1, 15, length.out = 15)),
                    ntree = 100)

  accuracy[i] <- sum(predict(rf_model, type = "raw") == cluster_assignment)
}

results <- cbind(iterations, positions, accuracy)

write.csv(results, "rf_position_combined.csv")
```




