---
title: "main"
author: "Zuofu Huang"
output: html_document
---

caret default classification metric is accuracy. Which is interesting, because they did not actually maximize accuracy

# Housekeeping

```{r message=FALSE}
library(dplyr)
library(caret)
library(clv)
# library(TraMineR)
# library(Matrix)
library(glmnet)
library(matrixcalc)

set.seed(7003)

data <- read.csv("/Users/zuofuhuang/Desktop/reduceSeq/Transportation data/cleaned_data_noNA.csv")[,-c(1:3)]
colnames(data) <- c(format(seq(as.POSIXct("00:00:00", format = "%T"), 
                 as.POSIXct("23:59:00", format = "%T"), by = "1 min"), "%H:%M"))

data <- data %>%
  mutate_if(is.character, as.factor)

extract_time <- function(string){
  as.numeric(substring(string, 2, 3)) * 60 + as.numeric(substring(string, 5, 6)) + 1
}
```


```{r}
source("/Users/zuofuhuang/Desktop/reduceSeq/Data-based grouping/clust_assign_func.R")

seq_distances <- read.csv("/Users/zuofuhuang/Desktop/reduceSeq/Transportation data/sequences_dist_matrix_om.csv")[,-1]

hclust_real <- stats::hclust(as.dist(seq_distances), method = "complete")
fit_real <- cutree(hclust_real, k = 23)
table(fit_real)


# cluster_assignment <- create_clusters_Dunn(seq_distances)
cluster_assignment <- reorder_cluster_assignment(fit_real)

# Consider cases where the groups are not consolidated down.
cluster_assignment[cluster_assignment > 14] <- 15
```



```{r}
set.seed(256)

positions_left_step2 <- 1:1440

unstable <- 1
n <- 0

n_variables_left <- c()
all_accuracy <- c()

while (unstable & n < 501){
  n <- n + 1
  data_reduced <- data[,positions_left_step2]
  data_reduced$CA <- cluster_assignment

  lasso_step2 <- train(as.factor(CA) ~ .,
                    data = data_reduced,
                    method = "glmnet",
                    family = "multinomial",
                    trControl = trainControl(method = "cv", number = 10),
                    tuneGrid = expand.grid(alpha = 1, lambda = seq(0, 0.05, length.out = 101)))

  # Record the accuracy first
  all_accuracy <- c(all_accuracy, sum(predict(lasso_step2, type = "raw") == cluster_assignment))
  
  lasso_step2_coefs <- coef(lasso_step2$finalModel, lasso_step2$finalModel$lambdaOpt)

  positions_left_step2 <- unique(c(
    extract_time((lasso_step2_coefs$`1`@Dimnames[[1]])[lasso_step2_coefs$`1`@i[which(abs((lasso_step2_coefs$`1`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`2`@Dimnames[[1]])[lasso_step2_coefs$`2`@i[which(abs((lasso_step2_coefs$`2`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`3`@Dimnames[[1]])[lasso_step2_coefs$`3`@i[which(abs((lasso_step2_coefs$`3`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`4`@Dimnames[[1]])[lasso_step2_coefs$`4`@i[which(abs((lasso_step2_coefs$`4`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`5`@Dimnames[[1]])[lasso_step2_coefs$`5`@i[which(abs((lasso_step2_coefs$`5`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`6`@Dimnames[[1]])[lasso_step2_coefs$`6`@i[which(abs((lasso_step2_coefs$`6`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`7`@Dimnames[[1]])[lasso_step2_coefs$`7`@i[which(abs((lasso_step2_coefs$`7`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`8`@Dimnames[[1]])[lasso_step2_coefs$`8`@i[which(abs((lasso_step2_coefs$`8`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`9`@Dimnames[[1]])[lasso_step2_coefs$`9`@i[which(abs((lasso_step2_coefs$`9`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`10`@Dimnames[[1]])[lasso_step2_coefs$`10`@i[which(abs((lasso_step2_coefs$`10`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`11`@Dimnames[[1]])[lasso_step2_coefs$`11`@i[which(abs((lasso_step2_coefs$`11`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`12`@Dimnames[[1]])[lasso_step2_coefs$`12`@i[which(abs((lasso_step2_coefs$`12`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`13`@Dimnames[[1]])[lasso_step2_coefs$`13`@i[which(abs((lasso_step2_coefs$`13`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`14`@Dimnames[[1]])[lasso_step2_coefs$`14`@i[which(abs((lasso_step2_coefs$`14`@x)) > 0)]]),
    extract_time((lasso_step2_coefs$`15`@Dimnames[[1]])[lasso_step2_coefs$`15`@i[which(abs((lasso_step2_coefs$`15`@x)) > 0)]])
))

  # NA occasionally introduced for picking up intercept
  positions_left_step2 <- na.omit(positions_left_step2)
  n_variables_left <- c(n_variables_left, length(positions_left_step2))
  
  if (length(n_variables_left) > 5){
    last_five <- tail(n_variables_left, 5)
    if (length(unique(last_five)) == 1){
      unstable <- 0
    }
  }
  
  print(length(positions_left_step2))
}

results <- as.data.frame(cbind(n_variables_left, all_accuracy))

write.csv(results, "n_variables_left.csv")
```


```{r}
results <- read.csv("n_variables_left.csv")
colnames(results) <- c("iteration", "Variables remaining")

ggplot(data = results, aes(x = iteration, y = `Variables remaining`)) + 
  geom_line() +
  xlab("Number of LASSO iterations") +
  ylab("Number of predictors remaining") + 
  ylim(c(0,1440)) +
  theme_bw()
```


