---
title: "Sparse Group LASSO Multivariate"
author: "Zuofu Huang"
date: "2024-02-21"
output: html_document
---

# Sparse Group LASSO

```{r message=FALSE}
library(caret)
library(tidyverse)
library(clv)
library(TraMineR)
library(matrixcalc)
library(grplasso)
library(fastDummies)
library(sparsegl)
```

```{r}
set.seed(7003)

data <- read.csv("/Users/zuofuhuang/Desktop/reduceSeq/Transportation data/cleaned_data_noNA.csv")[,-c(1:3)]
colnames(data) <- c(format(seq(as.POSIXct("00:00:00", format = "%T"), 
                 as.POSIXct("23:59:00", format = "%T"), by = "1 min"), "%H:%M"))

data <- data %>%
  mutate_if(is.character, as.factor)

extract_time2 <- function(string){
  as.numeric(substring(string, 1, 2)) * 60 + as.numeric(substring(string, 4, 5)) + 1
}
```

```{r}
source("../../clust_assign_func.R")

seq_distances <- read.csv("/Users/zuofuhuang/Desktop/reduceSeq/Transportation data/sequences_dist_matrix_om.csv")[,-1]


hclust_real <- stats::hclust(as.dist(seq_distances), method = "complete")
fit_real <- cutree(hclust_real, k = 23)
# table(fit_real)

# cluster_assignment <- create_clusters_Dunn(seq_distances)
cluster_assignment <- reorder_cluster_assignment(fit_real)

# Get rid of the really small "abnormalities" groups perhaps.
cluster_assignment[cluster_assignment > 14] <- 15
```

```{r}
data_wide <- fastDummies::dummy_cols(data, remove_selected_columns = T)

lasso_groups <- sapply(colnames(data_wide), extract_time2)
```

```{r}
convert <- function(assignments, goal){
  pos1 <- which(assignments == goal)
  pos2 <- which(assignments != goal)
  assignments[pos1] <- 1
  assignments[pos2] <- -1
  return(assignments)
}
```


# Sparse group lasso

```{r}
lambda_vec <- c(10^seq(from = -1, to = -6, length.out = 100))
```

We could use predict.cv.sparsegl to cross validate for binary and quantitative outcomes. However, we cannot do it here for multinomial outcomes because we need to first aggregate the binary prediction models together.

```{r}
# We could supply our own lambdas, or optionally use the function to get the list of lambda vlaues first.
# lambda_values <- sparsegl(as.matrix(data_wide), convert(cluster_assignment, 1),
#                 group = lasso_groups, intercept = F, family = "binomial")$lambda

# sparsegl <- sparsegl(as.matrix(data_wide), convert(cluster_assignment, 1),
#                 group = lasso_groups, intercept = F, family = "binomial")
# 
# coefs <- (sparsegl$beta)@x
# predict(sparsegl, new = as.matrix(data_wide), type = "response")
```

```{r}
sgl_once <- function(data, binary_outcome, lambda, lasso_group){
  sgl <- sparsegl(data, convert(cluster_assignment, binary_outcome), lambda = lambda,
                group = lasso_groups, intercept = F, family = "binomial")
  prob <- predict(sgl, new = data, type = "response")
  coefs <- sgl[["beta"]]
  return(list(prob, coefs))
}

sgl_perlambda <- function(data, clusters, lambda, lasso_group, cluster_assignment){
  results_perlambda <- lapply(clusters, FUN = sgl_once, data = data, lambda = lambda, lasso_group = lasso_group)
  probs_perlambda <- sapply(results_perlambda,"[[",1)
  coefs_perlambda <- sapply(results_perlambda,"[[",2)
  coefs_perlambda <- as.matrix(do.call(cbind, coefs_perlambda))
  
  assignment_perlambda <- apply(probs_perlambda, MARGIN = 1, FUN = which.max)
  accuracy <- sum(assignment_perlambda == cluster_assignment)
  return(list(accuracy, coefs_perlambda))
}

sgl_alllambda <- function(data, clusters, lambda_list, lasso_group, cluster_assignment){
  results_alllambda <- lapply(lambda_list, FUN = sgl_perlambda, data = data, clusters = clusters, lasso_group = lasso_groups, cluster_assignment = cluster_assignment)
  accuracy_alllambda <- sapply(results_alllambda,"[[",1)
  coefs_alllambda <- lapply(results_alllambda,"[[",2)
  return(list(accuracy_alllambda, coefs_alllambda))
}
```

```{r}
results <- sgl_alllambda(data = as.matrix(data_wide), clusters = 1:15, lambda_list = lambda_vec, lasso_group = lasso_groups, cluster_assignment = cluster_assignment)

# saved as results_sparsegl.RData
```


# Read saved results

```{r}
results <- readRDS("/Users/zuofuhuang/Desktop/reduceSeq/Data-based grouping/competitors/sparseGL/results_sparseGL")
# First in the list is the number of correct predictions for the corresponding lambda

```


# Get results out

```{r}
dummy_names <- colnames(data_wide)

get_nonzero_time <- function(vec, dummy_names){
  extract_time2(dummy_names[which(vec != 0)])
}

# count_nonzero_time <- function(vec, dummy_names){
#   length(extract_time2(dummy_names[which(vec != 0)]))
# }

count_nonzero_positions <- function(vec){
  length(unique(unlist(vec)))
}

accuracy <- results[[1]]

positions <- rep(NA, 100)
for (i in 1:100){
  positions[i] <- count_nonzero_positions(apply(results[[2]][[i]], 2, get_nonzero_time, dummy_names = dummy_names))
}

sparseGL_results_dat <- as.data.frame(cbind(lambda_vec, positions, accuracy))

# write.csv(sparseGL_results_dat, "sparseGL_results_dat.csv")
```
```{r}
sparseGL_results_dat <- read.csv("sparseGL_results_dat.csv")[,-1]
```


```{r}
library(ggplot2)

ggplot(sparseGL_results_dat, aes(x = positions, y = 1 - accuracy/2892)) +
  geom_point() + 
  geom_smooth(se = F) +
  xlab("Number of remaining positions") +
  ylab("Percent of correct classifications") +
  scale_x_reverse(breaks = seq(1440,0, by = -240)) +
  scale_y_continuous(lim = c(0, 0.3), breaks = seq(0, 0.3, 0.05)) + 
  theme_bw()
```





